name 'influxdb'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Installs/Configures influxdb'
version '0.1.8'
chef_version '>= 15.0'

source_url 'https://github.com/sous-chefs/influxdb'
issues_url 'https://github.com/sous-chefs/influxdb/issues'
