name             'sc-influxdb'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
chef_version     '>= 15.3'
version          '0.1.0'

description 'Resources for maintaining InfluxDB'
source_url  'https://github.com/sous-chefs/influxdb'
issues_url  'https://github.com/sous-chefs/influxdb/issues'
